### PR TITLE
oslo-config-generator support

### PR DESCRIPTION
**Pull request by kragniz**
This removes the old static config file and enables automatic generation using oslo-config-generator.

### CODE REVIEW

**Comment by sjmc7** [comment]
Looks good to me. If there's no dissent i'll merge this tomorrow.

**Comment by sigmavirus24** [comment]
On the contrary, I think this is fantastic. New services really shouldn't try to maintain an example conf file.

**Comment by sjmc7** [comment]
Yep. Some preexisting services have switched to this too, avoiding out of date and incomplete files. Ok, merging it.

**Comment by sigmavirus24** [comment]
I think Keystone might have something (like OpenStack Proposal Bot) that submits a new version every so many weeks. But it keeps it as etc/keystone.conf.example. I'm also not sure we want to start doing that.

**Pull request merged**
